export default [
    {
        title: 'Projeto CMS',
        img: 'https://raw.githubusercontent.com/GabrielDavid1/ProjetoCMS/main/public/imagemdosistema.png',
        type: 'Front-End',
        urlWebsite: 'https://projetocms-gabrieldavid75315-gmailcom.vercel.app',
        urlGithub: 'https://github.com/GabrielDavid1/ProjetoCMS',
        description: 'Screen projector, with this project it is possible to manipulate elements and through events change properties such as color, width, height, margin and etc.',
    },
    {
        title: 'Crud in VueJS with a FakeAPI',
        img: 'https://user-images.githubusercontent.com/87146770/160649168-cbd79a40-0e9c-44b5-badd-74650dfea8ac.png',
        type: 'Front-End',
        urlGithub: 'https://github.com/GabrielDavid1/CrudVueJS-FakeAPI',
        description: `It's a challenge project where I studied vuejs for 1 day based on documentation / tutorial and the next day I built an application with vue and vuetify.`,
    },
    {
        title: 'GdMoney',
        img: 'https://github.com/GabrielDavid1/GdMoney/blob/main/public/assets/img/screenshot.png?raw=true',
        type: 'Front-End',
        urlWebsite: 'https://gd-money.vercel.app',
        urlGithub: 'https://github.com/GabrielDavid1/GdMoney',
        description: 'Project to use cryptocurrency as a payment method in favor of blockchain. The goal was just to build the back-end but I ended up integrating with the front-end as well.',
    },
    {
        title: 'GdMoney API',
        img: 'https://thumbs.dreamstime.com/b/cryptocurrency-coin-bitcoin-arrow-chart-falling-doodle-style-isolated-217812860.jpg',
        type: 'Back-End',
        urlGithub: 'https://github.com/GabrielDavid1/GdMoney-API',
        description: 'Api built for my non-blockchain cryptocurrency payments project, it has user registration, token and refresh token system, authentication, payment persistence system and query to the binance api.',
    },
    {
        title: 'GDManagement',
        img: 'https://github.com/GabrielDavid1/GDManagement/blob/main/print.png?raw=true',
        type: 'Mobile',
        urlGithub: 'https://github.com/GabrielDavid1/GDManagement',
        description: 'Mobile project for product management and stock control. My focus on this project, in addition to putting mobile knowledge into practice, was also to improve my notion of ux design.',
    },
    {
        title: 'GDTools',
        img: `https://raw.githubusercontent.com/GabrielDavid1/GDTools/'main'/screen.png`,
        type: 'Front-End',
        urlWebsite: 'https://gd-tools.vercel.app',
        urlGithub: 'https://github.com/GabrielDavid1/GDTools',
        description: 'My best project in terms of code, planning and performance. I used my knowledge of months to focus on this project that aims to design mobile screens and convert web code to native (react native).',
    },
    {
        title: 'Autonomous App',
        img: 'https://github.com/GabrielDavid1/autonomous-app/blob/main/printscreen.png?raw=true',
        type: 'Design Ux Model',
        urlWebsite: 'https://www.figma.com/community/file/1138913953982140871',
        urlGithub: 'https://github.com/GabrielDavid1/autonomous-app',
        description: 'Template project to put into practice ux design notions. I built a model for a financial management app, selling/buying products.',
    },
    {
        title: 'GoPizza (Developed during the course)',
        img: 'https://github.com/GabrielDavid1/gopizza-react-native/blob/main/screenshotA.png?raw=true',
        type: 'Mobile',
        urlGithub: 'https://github.com/GabrielDavid1/gopizza-react-native',
        description: 'Project of a pizzeria app made in my full stack development course.',
    },   
    {
        title: 'Rentx (Developed during the course)',
        img: 'https://images-na.ssl-images-amazon.com/images/I/71rQR5ADySL.png',
        type: 'Back-End',
        urlGithub: 'https://github.com/GabrielDavid1/api-aluguel-carros',
        description: 'Project for a car rental application made in my full stack development course.',
    },    
    {
        title: 'Shopping Cart (Developed during the course)',
        img: 'https://nationaltoday.com/wp-content/uploads/2021/06/Shopping-Cart-Day-1.jpg',
        type: 'Front-End',
        urlGithub: 'https://github.com/GabrielDavid1/carrinhodecompras',
        description: 'Shopping cart project done in my full stack development course.',
    },
    {
        title: 'Deploy Test (Developed during the course)',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR0rnjZ8OkulUa9DQlFZRJbgMEAFkE9fVyFUApLIDts3r0j9gc1K7hRXwkTiOx8Sw8-1E&usqp=CAU',
        type: 'Front-End',
        urlWebsite: 'https://nextvercel-ruby-six.vercel.app',
        urlGithub: 'https://github.com/GabrielDavid1/nextvercel',
        description: 'Just my first deploy made on vercel.',
    },
];